version: "3"
services:

## This compose file will deploy:
##   1. Postgres + FerretDB Mongo adapter (https://www.ferretdb.com)
##   2. Komodo Core
##   3. Komodo Periphery
  postgres:
    image: postgres:17
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    restart: unless-stopped
    logging:
      driver: local
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${KOMODO_DB_USERNAME:-admin}
      - POSTGRES_PASSWORD=${KOMODO_DB_PASSWORD:-admin}
      - POSTGRES_DB=${KOMODO_DATABASE_DB_NAME:-komodo}

  ferretdb:
    image: ghcr.io/ferretdb/ferretdb:1
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    restart: unless-stopped
    depends_on:
      - postgres
    logging:
      driver: local
    environment:
      - FERRETDB_POSTGRESQL_URL=postgres://postgres:5432/${KOMODO_DATABASE_DB_NAME:-komodo}
  
  server:
    image: ghcr.io/moghtech/komodo-core:1.17.4
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    restart: unless-stopped
    depends_on:
      - ferretdb
    logging:
      driver: local
    ports:
      - 9120:9120
    environment:
      - KOMODO_TITLE=Komodo
      - KOMODO_DATABASE_URI=mongodb://${KOMODO_DB_USERNAME:-admin}:${KOMODO_DB_PASSWORD:-admin}@ferretdb:27017/${KOMODO_DATABASE_DB_NAME:-komodo}?authMechanism=PLAIN
      - KOMODO_PASSKEY=${KOMODO_PASSKEY:-komodo_passkey}
      - KOMODO_LOCAL_AUTH=true
      - KOMODO_WEBHOOK_SECRET=${KOMODO_WEBHOOK_SECRET:-komodo_webhook_secret}
      - KOMODO_JWT_SECRET=${KOMODO_JWT_SECRET:-komodo_jwt_secret}
      - KOMODO_JWT_TTL=${KOMODO_JWT_TTL:-1-day}
      - TZ=America/Sao_Paulo # Change this to your timezone
    volumes:
      - repo-cache:/repo-cache
  periphery:
    image: ghcr.io/moghtech/komodo-periphery:1.17.4
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    restart: unless-stopped
    logging:
      driver: local
    environment:
      - KOMODO_PASSKEY=${KOMODO_PASSKEY:-komodo_passkey}
      - PERIPHERY_ROOT_DIRECTORY=/etc/komodo
      - PERIPHERY_PASSKEYS=${KOMODO_PASSKEY:-komodo_passkey}
      - PERIPHERY_SSL_ENABLED=true
      - PERIPHERY_INCLUDE_DISK_MOUNTS=/etc/hostname
      - TZ=America/Sao_Paulo # Change this to your timezone
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/proc
      - /etc/komodo:/etc/komodo

volumes:
  # Postgres
  pg-data:
  # Core
  repo-cache: