version: "3"
services:
  app_proxy:
    environment:
      APP_HOST: brunov-swing-music_server_1
      APP_PORT: 1970
      PROXY_AUTH_ADD: "false"

  server:
    image: ghcr.io/swingmx/swingmusic:v1.4.8
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/config:/config
      - ${UMBREL_ROOT}/data/storage/downloads/music:/music:rw