version: '3'

services:
  api:
    image: clue/json-server
    ports:
      - "5000:80"
    command: >
      sh -c "echo '{\"info\":[{\"id\":1,\"status\":\"ok\",\"message\":\"test info\"}]}' > /data/db.json && json-server --watch /data/db.json --host 0.0.0.0 --port 80"

