version: '3'

services:
  api:
    image: python:3.12
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    command: >
      bash -c "pip install flask && python app.py"
